name: Build removestar

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SHELLOPTS: errexit:nounset:pipefail

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyflakes pytest pytest-doctestplus
      - name: Lint
        run: |
          pyflakes .
          python -We:invalid -We::SyntaxWarning -m compileall -f -q removestar/
      - name: Test
        run: |
          pytest
      - name: Install
        run: |
          # Make sure it installs
          python setup.py install
